#MarkSheet for HSSC part 2 students✌️💞 
#Remember me in your prays🤲.

n = input("Enter Name:\t ")
cl= input("Enter College:\t ")
r= int(input("Enter Roll no:\t "))
t= int(input("Enter total in HSSC|| no: "))
a= int(input("enter marks urdu: "))
b= int(input("enter marks english: "))
c= int(input("enter marks maths: "))
d= int(input("enter marks Computer science:"))
e= int(input("enter marks pak studies: "))
f= int(input("enter marks islamic studies: "))
g= int(input("enter marks physics: "))
print()
o= int(a+b+c+d+e+f+g)
p=float(o*100/t)
print("Name:","\t\t" ,n)
print("Class:","\t\t" ,cl)
print("Roll No:","\t" ,r)
print("="*80)
print("Subject","\t\t","T.Marks ","\t","O.Marks")
print("="*80)
print("Urdu","\t\t\t","200 ","\t\t",a)
print("English","\t\t","200 ","\t\t",b)
print("Maths","\t\t\t","200 ","\t\t",c)
print("Computer","\t\t","200 ","\t\t",d)
print("pak,Studies","\t\t","50 ","\t\t",e)
print("islamic studies","\t","50 ","\t\t",f)
print("physics","\t\t","200 ","\t\t",g)
print("="*80)
print("\t\t Total:",t,"\t","obtain:",o ,"\t  " "Percentage:",p,"%")
print("="*80)
