print(name)
Metric = int(input("Enter Metric marks : "))
inter = int(input("Enter inter marks : "))
D_O_B = (input("Enter date of Birthday : "))
Email = (input("Enter email address : "))
Password = (input("Choose a password : "))
Address = (input("Enter address : "))

print(name1)
Metric1 = int(input("Enter Metric marks : "))
inter1 = int(input("Enter inter marks : "))
D_O_B1 = (input("Enter date of Birthday : "))
Email1 = (input("Enter email address : "))
Password1 = (input("Choose a password : "))
Address1 = (input("Enter address : "))

print(name2)
Metric2 = int(input("Enter Metric marks : "))
inter2 = int(input("Enter inter marks : "))
D_O_B2 = (input("Enter date of Birthday : "))
Email2 = (input("Enter email address : "))
Password2 = (input("Choose a password : "))
Address2 = (input("Enter  address : "))

print(name3)
Metric3 = int(input("Enter Metric marks : "))
inter3 = int(input("Enter inter marks : "))
D_O_B3 = (input("Enter date of Birthday : "))
Email3 = (input("Enter email address : "))
Password3 = (input("Choose a password : "))
Address3 = (input("Enter  address : "))

print(name4)
Metric4 = int(input("Enter  Metric marks : "))
inter4 = int(input("Enter inter marks : "))
D_O_B4= (input("Enter date of Birthday : "))
Email4 = (input("Enter email address : "))
Password4 = (input("Choose a password : "))
Address4 = (input("Enter address : "))

print("**** Admission Form ***")

print(" ="*100)
print("  Metric Marks \t inter Marks \t (D_O_B) \t\t  Email \t\t   Password \t\t  Address\n","="*100,"\n",
      Metric ,  "\t\t\t", inter , "\t\t\t" , D_O_B , "\t\t" , Email , "\t\t" , Password , "\t\t" ,Address)
print(" ="*100)